[31merror[error]: 'number' object is not callable
----- Traceback -----
  â”Œâ”€ <unknown>:1:5
  | 
1 | 123()
  |      ^
[0m